import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    padding: 30,
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
  header: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#000000',
    paddingBottom: 10,
    marginBottom: 10,
  },
  logo: {
    width: 30,
    height: 30,
    marginRight: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#006400',
  },
  subTitle: {
    fontSize: 16,
    color: '#808080',
  },
  addressContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  address: {
    textAlign: 'right',
  },
  table: {
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#000000',
  },
  tableHeader: {
    backgroundColor: '#f0f0f0',
    borderBottomWidth: 1,
    borderBottomColor: '#000000',
    padding: 5,
    flexDirection: 'row',
  },
  tableRow: {
    flexDirection: 'row',
    padding: 5,
  },
  tableCell: {
    padding: 5,
  },
  tableCellRight: {
    textAlign: 'right',
  },
  tableCellCenter: {
    textAlign: 'center',
  },
  tableCellBold: {
    fontWeight: 'bold',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    color: 'grey',
    fontSize: 12,
  },
});

const InvoicePDF = ({ orderData, subtotal }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <View style={styles.header}>
          <Image
            style={styles.logo}
            source={{ uri: 'https://i.ibb.co/SBTB6sj/medicine.png' }}
          />
          <Text style={styles.title}>
            Ousodh<span style={{ color: 'black' }}>Chai</span>
          </Text>
        </View>
        <Text style={styles.subTitle}>Invoice</Text>
        <View style={styles.addressContainer}>
          <View>
            <Text>{orderData.name}</Text>
            <Text>{orderData.address}</Text>
            <Text>{orderData.city}, {orderData.country}</Text>
          </View>
          <View style={styles.address}>
            <Text>{`${dayName}, ${day} ${monthName}`}</Text>
            <Text>{year}</Text>
          </View>
        </View>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableCell, styles.tableCellBold]}>Item</Text>
            <Text style={[styles.tableCell, styles.tableCellCenter, styles.tableCellBold]}>Cost</Text>
            <Text style={[styles.tableCell, styles.tableCellCenter, styles.tableCellBold]}>Quantity</Text>
            <Text style={[styles.tableCell, styles.tableCellRight, styles.tableCellBold]}>Total</Text>
          </View>
          {orderData.products.map((item, index) => (
            <View style={styles.tableRow} key={index}>
              <Text style={[styles.tableCell]}>{item.name}</Text>
              <Text style={[styles.tableCell, styles.tableCellCenter]}>${item.price}</Text>
              <Text style={[styles.tableCell, styles.tableCellCenter]}>x{item.quantity}</Text>
              <Text style={[styles.tableCell, styles.tableCellRight]}>${item.price * item.quantity}</Text>
            </View>
          ))}
          <View style={[styles.tableRow, styles.tableCell]}>
            <Text style={[styles.tableCell, styles.tableCellBold]}></Text>
            <Text style={[styles.tableCell, styles.tableCellCenter, styles.tableCellBold]}></Text>
            <Text style={[styles.tableCell, styles.tableCellRight, styles.tableCellBold]}>Delivery Charge</Text>
            <Text style={[styles.tableCell, styles.tableCellRight]}>$10</Text>
          </View>
          <View style={[styles.tableRow, styles.tableCell]}>
            <Text style={[styles.tableCell, styles.tableCellBold]}></Text>
            <Text style={[styles.tableCell, styles.tableCellCenter, styles.tableCellBold]}></Text>
            <Text style={[styles.tableCell, styles.tableCellRight, styles.tableCellBold]}>Tax</Text>
            <Text style={[styles.tableCell, styles.tableCellRight]}>$5</Text>
          </View>
          <View style={[styles.tableRow, styles.tableCell]}>
            <Text style={[styles.tableCell, styles.tableCellBold]}></Text>
            <Text style={[styles.tableCell, styles.tableCellCenter, styles.tableCellBold]}></Text>
            <Text style={[styles.tableCell, styles.tableCellRight, styles.tableCellBold, { fontSize: 16 }]}>Sub Total</Text>
            <Text style={[styles.tableCell, styles.tableCellRight, styles.tableCellBold]}>${subtotal + 10 + 5}</Text>
          </View>
        </View>
        <Text style={styles.footer}>Generated by OusodhChai</Text>
      </View>
    </Page>
  </Document>
);

export default InvoicePDF;
